name: build-and-tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache composer packages
        uses: actions/cache@v2
        env:
          cache-name: v1-cache-composer-packages
        with:
          path: ./vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./composer.lock') }}
      - name: Install composer packages
        run: docker run --rm -v $(pwd):/app composer:2.0 install
   tests:
     runs-on: ubuntu-latest
     steps:
       - name: Run PHPUnit tests
         run: docker run --rm -v $(pwd):/app composer:2.0 run-script tests
